  TRUNCATE TABLE [DB_SSC_BC].[dbo].[books]
  TRUNCATE TABLE [DB_SSC_BC].[dbo].[fb_forms]
  TRUNCATE TABLE [DB_SSC_BC].[dbo].[fb_support]
  TRUNCATE TABLE [DB_SSC_BC].[dbo].[forms]
  TRUNCATE TABLE [DB_SSC_BC].[dbo].[forms_log]
  TRUNCATE TABLE [DB_SSC_BC].[dbo].[karma_log]
  TRUNCATE TABLE [DB_SSC_BC].[dbo].[subscriptions]
  TRUNCATE TABLE [DB_SSC_BC].[dbo].[users]